//
//  SyncCardsUseCase.swift
//  buntan
//
//  Created by 二木裕也 on 2025/10/04.
//

import Foundation

protocol SyncCardsUseCaseProtocol {
    func execute(loadingManager: LoadingManager) async -> Result<Void, SyncCardsUseCase.Error>
}

struct SyncCardsUseCase: SyncCardsUseCaseProtocol {
    
    enum Error: Swift.Error {
        case general(Swift.Error, canSkipDataFetching: Bool)
    }

    struct Dependency {
        let localDBVersionRepository: any LocalDBVersionRepositoryProtocol = LocalDBVersionRepository()
        let remoteConfigRepository: any RemoteConfigRepositoryProtocol = RemoteConfigRepository.shared
        let realmRepository: any RealmRepositoryProtocol = RealmRepository()
        let sheetService: any SheetServiceProtocol = SheetService()
    }

    private let dependency: Dependency
    
    init(dependency: Dependency = .init()) {
        self.dependency = dependency
    }
    
    func execute(loadingManager: LoadingManager) async -> Result<Void, Error> {
        let userDBVersionId = dependency.localDBVersionRepository.getValue(forKey: .usersCardsVersionId)
        do {
            let latestDBVersionId = try await dependency.remoteConfigRepository.string(.latestDBVersionId)
            if (latestDBVersionId != userDBVersionId) {
                await loadingManager.startLoading(.custom(message: "更新中..."))
                try await fetchLatestCards()
                dependency.localDBVersionRepository.setValue(value: latestDBVersionId, forKey: .usersCardsVersionId)
            } else {
                let delay: UInt64 = 3_000_000_000
                try await Task.sleep(nanoseconds: delay)
            }
            return .success(())
        } catch {
            return .failure(.general(error, canSkipDataFetching: userDBVersionId != nil))
        }
    }
    
    private func fetchLatestCards() async throws {
        let response = try await BuntanClient.getCardsLatest(config: AppConfig.shared)
        try dependency.sheetService.syncSheetCards(for: .first, with: response.firstGradeCards)
        try dependency.sheetService.syncSheetCards(for: .preFirst, with: response.preFirstGradeCards)
        /// To delete unnecessary objects generated by old app versions
        try deleteUnnecessaryObjects()
    }
    
    private func deleteUnnecessaryObjects() throws {
        let sheets: [Sheet] = try dependency.realmRepository.fetchAll()
        let necessaryCardIds = Set(sheets.flatMap { $0.cardList.map { $0.id } })
        let necessaryInfoIds = Set(sheets.flatMap { $0.cardList.flatMap { $0.infoList.map { $0.id } } })
        try dependency.realmRepository.deleteObjects(by: necessaryCardIds, of: RealmCard.self)
        try dependency.realmRepository.deleteObjects(by: necessaryInfoIds, of: RealmInfo.self)
    }
}
