# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

copyright("© #{Time.now.year} Yuya Niki")

submit_for_review(false)
automatic_release(false)
overwrite_screenshots(true)
