# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "buntan.xcodeproj")
    build_app(scheme: "buntan")
    upload_to_app_store(
      api_key_path: "fastlane/6322FU89DN.json",
      precheck_include_in_app_purchases: false
    )
  end

  lane :prepare_release do |options|
    # https://docs.fastlane.tools/actions/increment_version_number/
    version = increment_version_number(
      bump_type: options[:bump_type]
    )
    release_branch = "release/v#{version}"
    sh "git checkout -b #{release_branch}"
    
    # https://docs.fastlane.tools/actions/git_commit/#git_commit
    git_commit(
      path: "./buntan.xcodeproj/project.pbxproj",
      message: "chore: bump version to #{version}"
    )
    push_to_git_remote

    # https://docs.fastlane.tools/actions/create_pull_request/#create_pull_request
    create_pull_request(
      api_token: ENV["GITHUB_TOKEN"],
      repo: "nyoki610/buntan",
      title: "Release v#{version}",
      head: release_branch,
      base: "main"
    )

    create_pull_request(
      api_token: ENV["GITHUB_TOKEN"],
      repo: "nyoki610/buntan",
      title: "Release v#{version}",
      head: release_branch,
      base: "develop"
    )
  end
end
