# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    match(
      type: "appstore",
      readonly: true,
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
    )
    build_app(
      clean: true,
      scheme: "buntan",
      project: "buntan.xcodeproj",
      export_method: "app-store"
    )
    upload_to_app_store(
      api_key_path: "fastlane/6322FU89DN.json",
      precheck_include_in_app_purchases: false
    )
  end

  lane :prepare_release do |options|
    version = increment_version_number_in_xcodeproj(
      bump_type: options[:bump_type]
    )
    build_number = increment_build_number(xcodeproj: "buntan.xcodeproj")
    release_branch = "release/v#{version}"
    sh "git checkout -b #{release_branch}"
    git_commit(
      path: "./buntan.xcodeproj/project.pbxproj",
      message: "chore: bump version to #{version} (build #{build_number})"
    )
    push_to_git_remote
    create_pull_request(
      api_token: ENV["GITHUB_TOKEN"],
      repo: "nyoki610/buntan",
      title: "Release v#{version}",
      head: release_branch,
      base: "main",
      labels: ["release"]
    )
    create_pull_request(
      api_token: ENV["GITHUB_TOKEN"],
      repo: "nyoki610/buntan",
      title: "Release v#{version}",
      head: release_branch,
      base: "develop",
      labels: ["release"]
    )
  end
end
